import type { Yacht, WaterActivity } from '@/types';

export const yachts: Yacht[] = [
  {
    id: 'serenity-cruiser',
    name: 'Serenity Cruiser',
    category: 'private',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'luxury yacht',
    images: ['https://placehold.co/800x600.png', 'https://placehold.co/800x600.png', 'https://placehold.co/800x600.png'],
    capacity: 12,
    size: 85,
    description: 'Experience unparalleled luxury aboard the Serenity Cruiser. This 85-foot masterpiece of design and engineering offers spacious decks, a state-of-the-art sound system, and breathtaking views of the Dubai skyline. Perfect for exclusive parties, corporate events, or a lavish day out with family and friends.',
    pricePerHour: 2500,
    features: ['Spacious Flybridge', 'Sunbathing Area', 'Gourmet Galley', 'Air Conditioned Saloon', 'Premium Sound System'],
  },
  {
    id: 'ocean-dream',
    name: 'Ocean Dream',
    category: 'private',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'sleek yacht',
    images: ['https://placehold.co/800x600.png', 'https://placehold.co/800x600.png', 'https://placehold.co/800x600.png'],
    capacity: 10,
    size: 65,
    description: 'The Ocean Dream is the epitome of elegance and performance. Its sleek design cuts through the waves, providing a smooth and exhilarating journey. With comfortable seating and a modern interior, it\'s the ideal choice for smaller, more intimate gatherings.',
    pricePerHour: 1800,
    features: ['Modern Interior', 'Comfortable Seating', 'Swimming Platform', 'Experienced Crew'],
  },
  {
    id: 'gulf-explorer',
    name: 'Gulf Explorer',
    category: 'sharing',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'catamaran sunset',
    images: ['https://placehold.co/800x600.png', 'https://placehold.co/800x600.png', 'https://placehold.co/800x600.png'],
    capacity: 25,
    size: 70,
    description: 'Join a shared adventure on the Gulf Explorer. This spacious catamaran offers a stable and comfortable ride, with plenty of room to mingle and enjoy the stunning coastal sights. Our sharing trips are a fantastic way to meet new people and experience luxury yachting at an affordable price.',
    pricePerHour: 300,
    features: ['Large Deck Space', 'Social Atmosphere', 'Sightseeing Route', 'Complimentary Refreshments'],
  },
];

export const waterActivities: WaterActivity[] = [
  {
    id: 'jetski-thrills',
    name: 'Jetski',
    image: 'https://placehold.co/400x300.png',
    aiHint: 'jetski water',
    shortDescription: 'Feel the speed and splash across the waves.',
    longDescription: 'Unleash your inner thrill-seeker with our top-of-the-line jetskis. Feel the power as you zip across the turquoise waters of the Arabian Gulf, with the iconic Dubai skyline as your backdrop. Our experienced instructors provide a full safety briefing, ensuring a fun and safe experience for all skill levels.',
    price: 350,
    duration: 30,
  },
  {
    id: 'parasailing-heights',
    name: 'Parasailing',
    image: 'https://placehold.co/400x300.png',
    aiHint: 'parasailing sky',
    shortDescription: 'Soar high above the sea for breathtaking views.',
    longDescription: 'Get a bird\'s-eye view of Dubai\'s stunning coastline with our exhilarating parasailing experience. Safely harnessed, you\'ll ascend gently into the sky, enjoying panoramic vistas of the Palm Jumeirah, Burj Al Arab, and the endless blue sea. It\'s a peaceful yet thrilling adventure you won\'t forget.',
    price: 450,
    duration: 15,
  },
  {
    id: 'flyboard-flight',
    name: 'Flyboard',
    image: 'https://placehold.co/400x300.png',
    aiHint: 'flyboard action',
    shortDescription: 'Defy gravity and fly over the water like a superhero.',
    longDescription: 'Ever dreamed of flying? The Flyboard makes it a reality! Propelled by powerful water jets, you can soar above the sea, dive like a dolphin, and perform amazing aerial tricks. Our certified instructors will have you flying in no time, making this the ultimate water adventure.',
    price: 500,
    duration: 20,
  },
  {
    id: 'banana-boat-fun',
    name: 'Banana Ride',
    image: 'https://placehold.co/400x300.png',
    aiHint: 'banana boat',
    shortDescription: 'A wet and wild ride for the whole family.',
    longDescription: 'Hold on tight for a bouncy, splash-filled adventure on our classic Banana Boat! Towed by a speedboat, you and your friends will ride the waves, trying your best not to fall off. It\'s guaranteed laughter and fun for groups and families.',
    price: 150,
    duration: 15,
  },
   {
    id: 'jet-ski-car-ride',
    name: 'Jet Ski Car',
    image: 'https://placehold.co/400x300.png',
    aiHint: 'water car',
    shortDescription: 'Drive a car on the water for a unique experience.',
    longDescription: 'Experience the future of water sports with the incredible Jet Ski Car! It combines the thrill of a jetski with the look and feel of a luxury sports car, allowing you to cruise the Dubai coast in unparalleled style. Turn heads and create unforgettable memories.',
    price: 800,
    duration: 20,
  },
   {
    id: 'fishing-trip-dubai',
    name: 'Fishing Trips',
    image: 'https://placehold.co/400x300.png',
    aiHint: 'fishing boat',
    shortDescription: 'Cast a line and reel in the big one.',
    longDescription: 'Embark on a deep-sea fishing adventure in the rich waters of the Arabian Gulf. Our expert crew will guide you to the best fishing spots to catch Kingfish, Tuna, and more. We provide all the professional equipment you need for a successful day of sport fishing.',
    price: 1500,
    duration: 240,
  },
   {
    id: 'speed-boat-tour',
    name: 'Speed Boats',
    image: 'https://placehold.co/400x300.png',
    aiHint: 'speed boat',
    shortDescription: 'High-speed sightseeing tour of Dubai\'s icons.',
    longDescription: 'See Dubai\'s famous landmarks from a unique perspective on our thrilling speedboat tour. We\'ll zip past Atlantis The Palm, the Burj Al Arab, and the Dubai Marina, with plenty of photo opportunities along the way. It\'s the fastest and most exciting way to see the sights.',
    price: 600,
    duration: 60,
  },
   {
    id: 'scuba-diving-adventure',
    name: 'Scuba Diving',
    image: 'https://placehold.co/400x300.png',
    aiHint: 'scuba diving',
    shortDescription: 'Explore the underwater world of the Gulf.',
    longDescription: 'Discover the hidden marine life beneath the waves with our guided scuba diving trips. Whether you\'re a certified diver or a first-timer, our PADI-certified instructors will ensure a safe and memorable underwater journey, exploring local reefs and wrecks.',
    price: 550,
    duration: 180,
  },
   {
    id: 'kayaking-serenity',
    name: 'Kayaking',
    image: 'https://placehold.co/400x300.png',
    aiHint: 'kayak ocean',
    shortDescription: 'Paddle at your own pace and enjoy the tranquility.',
    longDescription: 'Enjoy a peaceful paddle along the Dubai shoreline with our stable and easy-to-use kayaks. It\'s a great way to get some exercise while enjoying the beautiful scenery at your own pace. Perfect for solo adventurers or couples looking for a relaxing escape.',
    price: 200,
    duration: 60,
  },
   {
    id: 'donut-ride-whirl',
    name: 'Donut Ride',
    image: 'https://placehold.co/400x300.png',
    aiHint: 'water tube',
    shortDescription: 'Spin and splash in this dizzying water ride.',
    longDescription: 'Get ready for a whirlwind of fun on the Donut Ride! This inflatable tube spins and bounces across the water as it\'s towed by a speedboat. It\'s a dizzying, delightful, and drenching experience that\'s sure to leave you smiling.',
    price: 150,
    duration: 15,
  },
];
