import type { Yacht, WaterActivity } from '@/types';

export const yachts: Yacht[] = [
  {
    id: 'serenity-cruiser-85',
    name: 'Serenity Cruiser (85ft)',
    category: 'private',
    image: '/images/yachts/private-yacht-1.jpg',
    aiHint: 'luxury yacht dubai',
    images: ['/images/yachts/private-yacht-1-1.jpg', '/images/yachts/private-yacht-1-2.jpg', '/images/yachts/private-yacht-1-3.jpg'],
    capacity: 25,
    size: 85,
    description: 'Experience unparalleled luxury aboard the Serenity Cruiser. This 85-foot masterpiece of design and engineering offers spacious decks, a state-of-the-art sound system, and breathtaking views of the Dubai skyline. Perfect for exclusive parties, corporate events, or a lavish day out with family and friends.',
    pricePerHour: 2500,
    features: ['Spacious Flybridge', 'Sunbathing Area', 'Gourmet Galley', 'Air Conditioned Saloon', 'Premium Sound System', '3 Bedrooms', 'Professional Crew'],
  },
  {
    id: 'ocean-dream-65',
    name: 'Ocean Dream (65ft)',
    category: 'private',
    image: '/images/yachts/private-yacht-2.jpg',
    aiHint: 'sleek modern yacht',
    images: ['/images/yachts/private-yacht-2-1.jpg', '/images/yachts/private-yacht-2-2.jpg'],
    capacity: 15,
    size: 65,
    description: 'The Ocean Dream is the epitome of elegance and performance. Its sleek design cuts through the waves, providing a smooth and exhilarating journey. With comfortable seating and a modern interior, it\'s the ideal choice for smaller, more intimate gatherings.',
    pricePerHour: 1800,
    features: ['Modern Interior', 'Comfortable Seating', 'Swimming Platform', 'Experienced Crew', '2 Bedrooms'],
  },
  {
    id: 'venus-yacht-55',
    name: 'Venus Yacht (55ft)',
    category: 'private',
    image: '/images/yachts/private-yacht-3.jpg',
    aiHint: 'family yacht charter',
    images: ['/images/yachts/private-yacht-3-1.jpg'],
    capacity: 12,
    size: 55,
    description: 'A perfect blend of comfort and style, the Venus is a 55ft yacht ideal for family outings or celebrations with friends. Enjoy the Dubai coastline in style.',
    pricePerHour: 1500,
    features: ['Sun Deck', 'Cozy Saloon', 'BBQ Grill', 'Music System'],
  },
  {
    id: 'gulf-explorer-catamaran-70',
    name: 'Gulf Explorer Catamaran (70ft)',
    category: 'sharing',
    image: '/images/yachts/sharing-yacht-1.jpg',
    aiHint: 'catamaran sunset cruise',
    images: ['/images/yachts/sharing-yacht-1-1.jpg', '/images/yachts/sharing-yacht-1-2.jpg'],
    capacity: 30,
    size: 70,
    description: 'Join a shared adventure on the Gulf Explorer. This spacious catamaran offers a stable and comfortable ride, with plenty of room to mingle and enjoy the stunning coastal sights. Our sharing trips are a fantastic way to meet new people and experience luxury yachting at an affordable price.',
    pricePerHour: 350,
    features: ['Large Deck Space', 'Social Atmosphere', 'Sightseeing Route', 'Live BBQ', 'Complimentary Refreshments'],
  },
  {
    id: 'dubai-sunset-cruise-50',
    name: 'Dubai Sunset Cruise (50ft)',
    category: 'sharing',
    image: '/images/yachts/sharing-yacht-2.jpg',
    aiHint: 'yacht sunset dubai',
    images: ['/images/yachts/sharing-yacht-2-1.jpg'],
    capacity: 20,
    size: 50,
    description: 'Witness the magical Dubai sunset from the deck of our comfortable sharing yacht. This 2-hour cruise offers spectacular views and a relaxing atmosphere.',
    pricePerHour: 250,
    features: ['Sunset Views', 'Relaxed Music', 'Snacks & Drinks', 'Photo Opportunities'],
  },
];

export const waterActivities: WaterActivity[] = [
  {
    id: 'jetski-thrills',
    name: 'Jetski',
    image: '/images/activities/jetski.jpg',
    aiHint: 'jetski water',
    shortDescription: 'Feel the speed and splash across the waves.',
    longDescription: 'Unleash your inner thrill-seeker with our top-of-the-line jetskis. Feel the power as you zip across the turquoise waters of the Arabian Gulf, with the iconic Dubai skyline as your backdrop. Our experienced instructors provide a full safety briefing, ensuring a fun and safe experience for all skill levels.',
    price: 350,
    duration: 30,
  },
  {
    id: 'parasailing-heights',
    name: 'Parasailing',
    image: '/images/activities/parasailing.jpg',
    aiHint: 'parasailing sky',
    shortDescription: 'Soar high above the sea for breathtaking views.',
    longDescription: 'Get a bird\'s-eye view of Dubai\'s stunning coastline with our exhilarating parasailing experience. Safely harnessed, you\'ll ascend gently into the sky, enjoying panoramic vistas of the Palm Jumeirah, Burj Al Arab, and the endless blue sea. It\'s a peaceful yet thrilling adventure you won\'t forget.',
    price: 450,
    duration: 15,
  },
  {
    id: 'flyboard-flight',
    name: 'Flyboard',
    image: '/images/activities/flyboard.jpg',
    aiHint: 'flyboard action',
    shortDescription: 'Defy gravity and fly over the water like a superhero.',
    longDescription: 'Ever dreamed of flying? The Flyboard makes it a reality! Propelled by powerful water jets, you can soar above the sea, dive like a dolphin, and perform amazing aerial tricks. Our certified instructors will have you flying in no time, making this the ultimate water adventure.',
    price: 500,
    duration: 20,
  },
  {
    id: 'banana-boat-fun',
    name: 'Banana Ride',
    image: '/images/activities/banana-boat.jpg',
    aiHint: 'banana boat',
    shortDescription: 'A wet and wild ride for the whole family.',
    longDescription: 'Hold on tight for a bouncy, splash-filled adventure on our classic Banana Boat! Towed by a speedboat, you and your friends will ride the waves, trying your best not to fall off. It\'s guaranteed laughter and fun for groups and families.',
    price: 150,
    duration: 15,
  },
   {
    id: 'jet-ski-car-ride',
    name: 'Jet Ski Car',
    image: '/images/activities/jet-car.jpg',
    aiHint: 'water car',
    shortDescription: 'Drive a car on the water for a unique experience.',
    longDescription: 'Experience the future of water sports with the incredible Jet Ski Car! It combines the thrill of a jetski with the look and feel of a luxury sports car, allowing you to cruise the Dubai coast in unparalleled style. Turn heads and create unforgettable memories.',
    price: 800,
    duration: 20,
  },
   {
    id: 'fishing-trip-dubai',
    name: 'Fishing Trips',
    image: '/images/activities/fishing.jpg',
    aiHint: 'fishing boat',
    shortDescription: 'Cast a line and reel in the big one.',
    longDescription: 'Embark on a deep-sea fishing adventure in the rich waters of the Arabian Gulf. Our expert crew will guide you to the best fishing spots to catch Kingfish, Tuna, and more. We provide all the professional equipment you need for a successful day of sport fishing.',
    price: 1500,
    duration: 240,
  },
   {
    id: 'speed-boat-tour',
    name: 'Speed Boats',
    image: '/images/activities/speedboat.jpg',
    aiHint: 'speed boat',
    shortDescription: 'High-speed sightseeing tour of Dubai\'s icons.',
    longDescription: 'See Dubai\'s famous landmarks from a unique perspective on our thrilling speedboat tour. We\'ll zip past Atlantis The Palm, the Burj Al Arab, and the Dubai Marina, with plenty of photo opportunities along the way. It\'s the fastest and most exciting way to see the sights.',
    price: 600,
    duration: 60,
  },
   {
    id: 'donut-ride-whirl',
    name: 'Donut Ride',
    image: '/images/activities/donut-ride.jpg',
    aiHint: 'water tube',
    shortDescription: 'Spin and splash in this dizzying water ride.',
    longDescription: 'Get ready for a whirlwind of fun on the Donut Ride! This inflatable tube spins and bounces across the water as it\'s towed by a speedboat. It\'s a dizzying, delightful, and drenching experience that\'s sure to leave you smiling.',
    price: 150,
    duration: 15,
  },
];
